spring:
   datasource:
       url: jdbc:mariadb://localhost:3306/test
       driverClassName: org.mariadb.jdbc.Driver
       username: root
       password: root
   jpa:
       database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
       hibernate:
           ddl-auto: update
       show-sql: true
server:
   port: 9000




    